name: "Build and push Super Nario Docker image with static tag to Docker Hub"

# on:
#   push:
#     branches:
#       - main
env:
  VERSION: $(( $(cat version.txt) + 1 ))

jobs:
  build_and_push_supermario_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
     
      - name: Build Docker image
        run: |
          docker build -t docker.io/alandocker97/supermariogitopsproject:${{ env.VERSION }} .
     
      - name: Push Docker image
        run: |
          docker push docker.io/alandocker97/supermariogitopsproject:${{ env.VERSION }}