name: "Run Container Scan on Super Mario Docker Image with Quality Gate"
 
on:
  push:
    branches:
      - main
 
env:
  VERSION: $(( $(cat version.txt) + 1 ))
  
jobs:
  
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest	
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
 
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
        
      - name: Get Docker Image from Docker Hub
        run: |
          docker pull docker.io/alandocker97/supermariogitopsproject:${{ env.VERSION }}
          docker save -o supermariolatestdockerimage.tar docker.io/alandocker97/supermariogitopsproject:${{ env.VERSION }}
     
          echo "Verifying saved tarball in current directory ($(pwd)):"
          if [ -f "supermariolatestdockerimage.tar" ]; then
            echo "SUCCESS: supermariolatestdockerimage.tar found!"
            ls -lh supermariolatestdockerimage.tar
          else
            echo "ERROR: supermariolatestdockerimage.tar NOT found in $(pwd)!"
            echo "Current directory contents:"
            ls -lA
            exit 1 # Fail the workflow if the tarball isn't created
          fi

      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
          input: '${{ github.workspace }}/supermariolatestdockerimage.tar'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'